DROP DATABASE IF EXISTS CreditosVerdes;
CREATE DATABASE CreditosVerdes
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;
USE CreditosVerdes;
-- 1) CATÁLOGOS
CREATE TABLE ROL (
  id_rol INT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  descripcion VARCHAR(255),
  UNIQUE KEY uq_rol_nombre (nombre)
);

CREATE TABLE UNIDAD_MEDIDA (
  id_um INT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  simbolo VARCHAR(10) NOT NULL,
  UNIQUE KEY uq_um_nombre (nombre),
  UNIQUE KEY uq_um_simbolo (simbolo)
);

CREATE TABLE TIPO_MOVIMIENTO (
  id_tipo_mov INT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  signo ENUM('IN','OUT') NOT NULL,
  descripcion VARCHAR(255),
  UNIQUE KEY uq_tipo_mov_nombre (nombre)
);

CREATE TABLE TIPO_BITACORA (
  id_tipo_bit INT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(50) NOT NULL,
  descripcion VARCHAR(255),
  UNIQUE KEY uq_tipo_bit_nombre (nombre)
);
-- 2) USUARIOS Y SEGURIDAD
CREATE TABLE USUARIO (
  id_us INT PRIMARY KEY AUTO_INCREMENT,
  id_rol INT NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  apellido VARCHAR(100) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  telefono VARCHAR(25),
  direccion VARCHAR(255),
  fecha_registro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY (id_rol) REFERENCES ROL(id_rol)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ;

CREATE TABLE ACCESO (
  id_acc INT PRIMARY KEY AUTO_INCREMENT,
  id_us INT NOT NULL,
  fecha_acc DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  exito BOOLEAN NOT NULL,
  ip VARCHAR(45),
  agente VARCHAR(500),
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE CASCADE
) ;

-- Hash moderno + compatibilidad legacy
CREATE TABLE CONTRASENA (
  id_cmb INT PRIMARY KEY AUTO_INCREMENT,
  id_us INT UNIQUE NOT NULL,
  algoritmo ENUM('BCRYPT','ARGON2ID','LEGACY') NOT NULL DEFAULT 'BCRYPT',
  hash_legacy VARBINARY(255) NULL,
  hash CHAR(60) NULL, -- bcrypt
  fecha_cambio DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE CASCADE
) ;

CREATE TABLE BILLETERA (
  id_us INT PRIMARY KEY,
  cuenta_bancaria VARCHAR(100),
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE CASCADE
);
-- 3) UBICACIÓN
CREATE TABLE UBICACION (
  id_ub INT PRIMARY KEY AUTO_INCREMENT,
  direccion VARCHAR(500) NOT NULL,
  ciudad VARCHAR(100),
  provincia VARCHAR(100),
  lat DECIMAL(9,6),
  lon DECIMAL(9,6)
) ;
-- 4) CATEGORÍAS
CREATE TABLE CATEGORIA (
  id_cat INT PRIMARY KEY AUTO_INCREMENT,
  tipo ENUM('PRODUCTO','SERVICIO') NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  descripcion VARCHAR(255),
  creado_por INT NULL,
  actualizado_por INT NULL,
  UNIQUE KEY uq_categoria_tipo_nombre (tipo, nombre),
  FOREIGN KEY (creado_por) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (actualizado_por) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL
) ;
-- 5) PRODUCTOS Y SERVICIOS
CREATE TABLE PRODUCTO (
  id_prod INT PRIMARY KEY AUTO_INCREMENT,
  id_cat INT NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  descripcion VARCHAR(255),
  precio DECIMAL(15,2) NOT NULL,
  peso DECIMAL(10,2),
  creado_por INT NULL,
  actualizado_por INT NULL,
  FOREIGN KEY (id_cat) REFERENCES CATEGORIA(id_cat)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (creado_por) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (actualizado_por) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL
) ;

CREATE TABLE SERVICIO (
  id_serv INT PRIMARY KEY AUTO_INCREMENT,
  id_cat INT NOT NULL,
  id_us INT NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  descripcion TEXT,
  precio DECIMAL(15,2) NOT NULL,
  duracion_min SMALLINT,
  estado ENUM('ACTIVO','PAUSADO','INACTIVO','ELIMINADO') NOT NULL DEFAULT 'ACTIVO',
  creado_por INT NULL,
  actualizado_por INT NULL,
  FOREIGN KEY (id_cat) REFERENCES CATEGORIA(id_cat)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (creado_por) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (actualizado_por) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL
);
-- 6) PUBLICACIONES
CREATE TABLE PUBLICACION (
  id_pub INT PRIMARY KEY AUTO_INCREMENT,
  id_us INT NOT NULL,
  id_ub INT NOT NULL,
  tipo ENUM('PRODUCTO','SERVICIO') NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  descripcion TEXT,
  valor_creditos DECIMAL(15,2) NOT NULL DEFAULT 0,
  estado ENUM('BORRADOR','PUBLICADA','PAUSADA','AGOTADA','OCULTA','ELIMINADA')
         NOT NULL DEFAULT 'PUBLICADA',
  fecha_pub DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_act DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  creado_por INT NULL,
  actualizado_por INT NULL,
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_ub) REFERENCES UBICACION(id_ub)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (creado_por) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (actualizado_por) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL
) ;

CREATE TABLE PUBLICACION_PRODUCTO (
  id_pub INT,
  id_prod INT,
  cantidad DECIMAL(15,4) NOT NULL,
  id_um INT NOT NULL,
  PRIMARY KEY (id_pub, id_prod),
  FOREIGN KEY (id_pub) REFERENCES PUBLICACION(id_pub)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (id_prod) REFERENCES PRODUCTO(id_prod)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_um) REFERENCES UNIDAD_MEDIDA(id_um)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ;

CREATE TABLE PUBLICACION_SERVICIO (
  id_pub INT,
  id_serv INT,
  horario VARCHAR(100) NOT NULL,
  PRIMARY KEY (id_pub, id_serv),
  FOREIGN KEY (id_pub) REFERENCES PUBLICACION(id_pub)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (id_serv) REFERENCES SERVICIO(id_serv)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ;
-- 7) PROMOCIONES
CREATE TABLE PROMOCION (
  id_prom INT PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(255) NOT NULL,
  descripcion VARCHAR(255),
  fecha_ini DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  banner VARCHAR(500),
  descuento DECIMAL(5,2) NOT NULL,
  estado ENUM('PROGRAMADA','ACTIVA','PAUSADA','FINALIZADA') NOT NULL DEFAULT 'PROGRAMADA',
  creado_por INT NULL,
  actualizado_por INT NULL,
  FOREIGN KEY (creado_por) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (actualizado_por) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL
) ;

CREATE TABLE PROMOCION_APLICA (
  id_prom INT NOT NULL,
  entidad ENUM('PRODUCTO','SERVICIO') NOT NULL,
  id_entidad INT NOT NULL,
  PRIMARY KEY (id_prom, entidad, id_entidad),
  FOREIGN KEY (id_prom) REFERENCES PROMOCION(id_prom)
    ON UPDATE CASCADE ON DELETE CASCADE
) ;
-- 8) CRÉDITOS / INTERCAMBIOS / TRANSACCIONES
CREATE TABLE PAQUETE_CREDITO (
  id_paquete INT PRIMARY KEY AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  cantidad_creditos INT NOT NULL,
  precio DECIMAL(15,2) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE KEY uq_paquete_nombre (nombre)
) ;

CREATE TABLE COMPRA_CREDITO (
  id_compra INT PRIMARY KEY AUTO_INCREMENT,
  id_us INT NOT NULL,
  id_paquete INT NOT NULL,
  creditos INT NOT NULL,
  monto DECIMAL(15,2) NOT NULL,
  proveedor VARCHAR(100) NOT NULL,
  referencia VARCHAR(100),
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  aprobado_en DATETIME,
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_paquete) REFERENCES PAQUETE_CREDITO(id_paquete)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ;

CREATE TABLE INTERCAMBIO (
  id_inter INT PRIMARY KEY AUTO_INCREMENT,
  id_us_comp INT NOT NULL,
  id_us_vend INT NOT NULL,
  id_pub INT NOT NULL,
  id_ub_origen INT NOT NULL,
  id_ub_destino INT NOT NULL,
  id_um INT NULL,
  cantidad DECIMAL(15,4) NOT NULL,
  costo_reembolso DECIMAL(15,2),
  fecha_sol DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_acept DATETIME,
  fecha_comp DATETIME,
  estado ENUM('SOLICITADO','ACEPTADO','RECHAZADO','CANCELADO','COMPLETADO') NOT NULL DEFAULT 'SOLICITADO',
  FOREIGN KEY (id_us_comp) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_us_vend) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_pub) REFERENCES PUBLICACION(id_pub)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_ub_origen) REFERENCES UBICACION(id_ub)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_ub_destino) REFERENCES UBICACION(id_ub)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_um) REFERENCES UNIDAD_MEDIDA(id_um)
    ON UPDATE CASCADE ON DELETE SET NULL
) ;

CREATE TABLE TRANSACCION (
  id_trans INT PRIMARY KEY AUTO_INCREMENT,
  id_us INT NOT NULL,
  id_us2 INT NOT NULL,
  id_inter INT,
  fecha_trans DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  monto DECIMAL(15,2) NOT NULL,
  estado ENUM('PENDIENTE','CONFIRMADA','ANULADA','FALLIDA') NOT NULL DEFAULT 'PENDIENTE',
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_us2) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_inter) REFERENCES INTERCAMBIO(id_inter)
    ON UPDATE CASCADE ON DELETE SET NULL
) ;

CREATE TABLE MOVIMIENTO (
  id_mov INT PRIMARY KEY AUTO_INCREMENT,
  id_us INT NOT NULL,
  id_tipo_mov INT NOT NULL,
  cantidad DECIMAL(15,2) NOT NULL,
  fecha_mov DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  descripcion VARCHAR(255),
  id_inter INT,
  id_compra INT,
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_tipo_mov) REFERENCES TIPO_MOVIMIENTO(id_tipo_mov)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_inter) REFERENCES INTERCAMBIO(id_inter)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (id_compra) REFERENCES COMPRA_CREDITO(id_compra)
    ON UPDATE CASCADE ON DELETE SET NULL
) ;
-- 9) RECOMPENSAS / REPORTES / BITÁCORA
CREATE TABLE RECOMPENSA (
  id_rec INT PRIMARY KEY AUTO_INCREMENT,
  tipo VARCHAR(50) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  monto DECIMAL(15,2) NOT NULL
) ;

CREATE TABLE USUARIO_LOGRO (
  id_us INT,
  id_rec INT,
  fecha_obtencion DATE NOT NULL,
  PRIMARY KEY (id_us, id_rec),
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (id_rec) REFERENCES RECOMPENSA(id_rec)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ;

CREATE TABLE REPORTE (
  id_reporte INT PRIMARY KEY AUTO_INCREMENT,
  id_reportante INT NOT NULL,
  id_usuario_reportado INT,
  id_pub_reportada INT,
  motivo VARCHAR(500) NOT NULL,
  fecha_reporte DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  id_admin_resuelve INT,
  estado ENUM('ABIERTO','EN_REVISION','RESUELTO','DESCARTADO') NOT NULL DEFAULT 'ABIERTO',
  FOREIGN KEY (id_reportante) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_usuario_reportado) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (id_pub_reportada) REFERENCES PUBLICACION(id_pub)
    ON UPDATE CASCADE ON DELETE SET NULL,
  FOREIGN KEY (id_admin_resuelve) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL
) ;

CREATE TABLE BITACORA (
  id_bitacora INT PRIMARY KEY AUTO_INCREMENT,
  id_tipo_bit INT NOT NULL,
  id_us INT,
  entidad VARCHAR(100) NOT NULL,
  id_entidad INT,
  accion VARCHAR(100) NOT NULL,
  descripcion VARCHAR(500),
  ip VARCHAR(45),
  fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_tipo_bit) REFERENCES TIPO_BITACORA(id_tipo_bit)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE SET NULL
);
-- 10) MÓDULO AMBIENTAL
CREATE TABLE DIMENSION_AMBIENTAL (
  id_dim INT PRIMARY KEY AUTO_INCREMENT,
  codigo VARCHAR(30) NOT NULL UNIQUE,
  nombre VARCHAR(100) NOT NULL,
  unidad_base VARCHAR(20) DEFAULT 'kg',
  descripcion VARCHAR(255)
) ;

CREATE TABLE FACTOR_CONVERSION (
  id_factor INT PRIMARY KEY AUTO_INCREMENT,
  id_dim INT NOT NULL,
  id_um_origen INT NOT NULL,
  id_um_dest INT NOT NULL,
  factor DECIMAL(18,8) NOT NULL,
  descripcion VARCHAR(255),
  FOREIGN KEY (id_dim) REFERENCES DIMENSION_AMBIENTAL(id_dim)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_um_origen) REFERENCES UNIDAD_MEDIDA(id_um)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_um_dest) REFERENCES UNIDAD_MEDIDA(id_um)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ;

CREATE TABLE EVENTO_AMBIENTAL (
  id_evento INT PRIMARY KEY AUTO_INCREMENT,
  id_us INT NOT NULL,
  id_dim INT NOT NULL,
  fuente ENUM('PUBLICACION','INTERCAMBIO') NOT NULL,
  id_fuente INT NOT NULL,
  categoria VARCHAR(100),
  valor DECIMAL(18,6) NOT NULL,
  id_um INT NOT NULL,
  contaminacion_reducida DECIMAL(18,6) COMMENT 'Equivalente',
  descripcion VARCHAR(255),
  creado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_dim) REFERENCES DIMENSION_AMBIENTAL(id_dim)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_um) REFERENCES UNIDAD_MEDIDA(id_um)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ;

CREATE TABLE IMPACTO_MENSUAL (
  anio SMALLINT NOT NULL,
  mes TINYINT NOT NULL,
  id_us INT NOT NULL,
  id_dim INT NOT NULL,
  valor_total DECIMAL(18,6) NOT NULL DEFAULT 0,
  contaminacion_reducida_total DECIMAL(18,6) COMMENT 'Total (kg CO₂e)',
  actualizado_en DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (anio, mes, id_us, id_dim),
  FOREIGN KEY (id_us) REFERENCES USUARIO(id_us)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (id_dim) REFERENCES DIMENSION_AMBIENTAL(id_dim)
    ON UPDATE CASCADE ON DELETE RESTRICT
);
-- 11) ÍNDICES DE RENDIMIENTO
-- PUBLICACION
CREATE INDEX idx_publicacion_estado        ON PUBLICACION(estado);
CREATE INDEX idx_publicacion_idus_estado   ON PUBLICACION(id_us, estado);
CREATE INDEX idx_publicacion_fecha_act     ON PUBLICACION(fecha_act);
-- SERVICIO
CREATE INDEX idx_servicio_estado           ON SERVICIO(estado);
CREATE INDEX idx_servicio_idus_estado      ON SERVICIO(id_us, estado);
-- INTERCAMBIO
CREATE INDEX idx_intercambio_estado        ON INTERCAMBIO(estado);
CREATE INDEX idx_intercambio_comp_vend     ON INTERCAMBIO(id_us_comp, id_us_vend);
CREATE INDEX idx_intercambio_fecha_sol     ON INTERCAMBIO(fecha_sol);
-- MOVIMIENTO
CREATE INDEX idx_movimiento_idus           ON MOVIMIENTO(id_us);
CREATE INDEX idx_movimiento_tipo           ON MOVIMIENTO(id_tipo_mov);
CREATE INDEX idx_movimiento_fecha          ON MOVIMIENTO(fecha_mov);
-- TRANSACCION
CREATE INDEX idx_transaccion_estado        ON TRANSACCION(estado);
CREATE INDEX idx_transaccion_us_us2        ON TRANSACCION(id_us, id_us2);
CREATE INDEX idx_transaccion_fecha         ON TRANSACCION(fecha_trans);
-- PUBLICACION_PRODUCTO
CREATE INDEX idx_pubprod_prod              ON PUBLICACION_PRODUCTO(id_prod);
CREATE INDEX idx_pubprod_um                ON PUBLICACION_PRODUCTO(id_um);
-- REPORTE
CREATE INDEX idx_reporte_estado            ON REPORTE(estado);
CREATE INDEX idx_reporte_fecha             ON REPORTE(fecha_reporte);
-- EVENTO_AMBIENTAL / IMPACTO_MENSUAL
CREATE INDEX idx_evento_ambiental_us_dim   ON EVENTO_AMBIENTAL(id_us, id_dim);
CREATE INDEX idx_evento_ambiental_fecha    ON EVENTO_AMBIENTAL(creado_en);
CREATE INDEX idx_impacto_mensual_us_dim    ON IMPACTO_MENSUAL(id_us, id_dim);
-- ACCESO / BITACORA
CREATE INDEX idx_acceso_us_fecha           ON ACCESO(id_us, fecha_acc);
CREATE INDEX idx_bitacora_tipo_fecha       ON BITACORA(id_tipo_bit, fecha);
CREATE INDEX idx_bitacora_entidad          ON BITACORA(entidad, id_entidad);
