CREATE DATABASE SISTEMA_DE_TRUEQUE;

USE SISTEMA_DE_TRUEQUE;

CREATE TABLE USUARIO (
    ID_USUARIO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_USU VARCHAR(100) NOT NULL,
    APELLIDO_USU VARCHAR(100) NOT NULL,
    CORREO_USU VARCHAR(150) UNIQUE NOT NULL,
    CONTRASEÑA_USU VARCHAR(255) NOT NULL,
    TELEFONO_USU VARCHAR(20),
    DIRECCION_USU TEXT,
    FECHA_REGISTRO_USU DATETIME DEFAULT CURRENT_TIMESTAMP,
    ROL_USU ENUM('admin', 'usuario', 'moderador') DEFAULT 'usuario',
    SALDO_CREDITOS_USU DECIMAL(10,2) DEFAULT 0.00,
    ESTADO ENUM('activo', 'inactivo', 'suspendido') DEFAULT 'activo',
    INDEX IDX_CORREO (CORREO_USU),
    INDEX IDX_ESTADO (ESTADO)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE_CAT VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION_CAT TEXT,
    FACTOR_CO2 DECIMAL(8,4) DEFAULT 1.0000,
    INDEX IDX_NOMBRE (NOMBRE_CAT)
);

CREATE TABLE PUBLICACION (
    ID_PUBLICACION INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    TITULO_PUB VARCHAR(200) NOT NULL,
    DESCRIPCION_PUB TEXT,
    VALOR_CREDITO DECIMAL(10,2) NOT NULL,
    ESTADO_PUB ENUM('activa', 'inactiva', 'vendida', 'eliminada') DEFAULT 'activa',
    FECHA_PUB DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION_PUB DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA) ON DELETE RESTRICT,
    INDEX IDX_ESTADO_PUB (ESTADO_PUB),
    INDEX IDX_FECHA_PUB (FECHA_PUB),
    INDEX IDX_CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE INTERCAMBIO (
    ID_INTERCAMBIO INT PRIMARY KEY AUTO_INCREMENT,
    ID_PUBLICACION INT NOT NULL,
    ID_COMPRADOR INT NOT NULL,
    ID_VENDEDOR INT NOT NULL,
    FECHA_SOLICITUD_CAMBIO DATETIME DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACEPTACION_CAMBIO DATETIME NULL,
    FECHA_CONMPLETACION_CAMBIO DATETIME NULL,
    CANTIDAD_CREDITOS DECIMAL(10,2) NOT NULL,
    ESTADO_CAMBIO ENUM('solicitado', 'aceptado', 'rechazado', 'completado', 'cancelado') DEFAULT 'solicitado',
    FOREIGN KEY (ID_PUBLICACION) REFERENCES PUBLICACION(ID_PUBLICACION) ON DELETE CASCADE,
    FOREIGN KEY (ID_COMPRADOR) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY (ID_VENDEDOR) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    INDEX IDX_ESTADO_CAMBIO (ESTADO_CAMBIO),
    INDEX IDX_FECHA_SOLICITUD_CAMBIO (FECHA_SOLICITUD_CAMBIO),
    INDEX IDX_COMPRADOR (ID_COMPRADOR),
    INDEX IDX_VENDEDOR (ID_VENDEDOR)
);

CREATE TABLE MOVIMIENTO_CREDITOS (
    ID_MOVIMIENTO INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NOT NULL,
    TIPO_MOV ENUM('compra', 'venta', 'recarga', 'retiro', 'transferencia') NOT NULL,
    CANTIDAD DECIMAL(10,2) NOT NULL,
    FECHA_MOV DATETIME DEFAULT CURRENT_TIMESTAMP,
    DESCRIPCION_MOV VARCHAR(255),
    ID_REFERENCIA_MOV INT NULL,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE CASCADE,
    INDEX IDX_FECHA_MOV (FECHA_MOV),
    INDEX IDX_TIPO_MOV (TIPO_MOV),
    INDEX IDX_USUARIO (ID_USUARIO)
);

CREATE TABLE BITACORA (
    ID_BITACORA INT PRIMARY KEY AUTO_INCREMENT,
    ID_USUARIO INT NULL,
    TABLA_AFECTADA VARCHAR(50) NOT NULL,
    ACCION_BIT ENUM('INSERT', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'ERROR') NOT NULL,
    DESCRIPCION_BIT TEXT,
    DATOS_ANTERIORES JSON NULL,
    DATOS_NUEVOS JSON NULL,
    FECHA_EVENTO_BIT DATETIME DEFAULT CURRENT_TIMESTAMP,
    IP_DIRECCION VARCHAR(45),
    USUARIO_AGENTE VARCHAR(255),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO) ON DELETE SET NULL,
    INDEX IDX_TABLA_AFECTADA (TABLA_AFECTADA),
    INDEX IDX_ACCION_BIT (ACCION_BIT),
    INDEX IDX_FECHA_EVENTO_BIT (FECHA_EVENTO_BIT),
    INDEX IDX_USUARIO (ID_USUARIO)
);